services:
  xtts:
    build: .
    image: local-xtts:latest
    container_name: xtts
    environment:
      - TTS_PORT=${TTS_PORT:-5002}
      - COQUI_TOS_AGREED=${COQUI_TOS_AGREED:-1}
      - DEFAULT_VOICE=${DEFAULT_VOICE:-}
    volumes:
      - ./cache:/root/.local/share/tts
      - ./voices:/voices:ro
    networks:
      - fortress-phronesis-net
    restart: unless-stopped
    ports:
      - "${TTS_BIND_IP:-0.0.0.0}:${TTS_PORT:-5002}:${TTS_PORT:-5002}"

networks:
  fortress-phronesis-net:
    external: true
