version: "3.9"
services:
  xtts:
    build: .
    image: local-xtts:latest
    container_name: xtts
    environment:
      - MODEL_NAME=${MODEL_NAME:-tts_models/multilingual/multi-dataset/xtts_v2}
      - TTS_PORT=${TTS_PORT:-5002}
      - COQUI_TOS_AGREED=${COQUI_TOS_AGREED:-1}
    volumes:
      - ./cache:/root/.local/share/tts
    networks:
      - fortress-phronesis-net
    restart: unless-stopped
    ports:
      - "${TTS_BIND_IP:-0.0.0.0}:${TTS_PORT:-5002}:${TTS_PORT:-5002}"

networks:
  fortress-phronesis-net:
    external: true
